fastify/fastify-auth

README.md, example.js, fastify-auth.js, package.json, test.js
@delvedor what do you think?
There are a bunch of TODOs, and it will probably require more testing.
Do you think we can easily use the `'onRequest'` hook to apply this to protect all routes in a plugin?
=> Made auth support generic

example.js
=> Updated example.js

README.md
Clarification for example snippet and link to full example in README, as discussed in https://github.com/fastify/fastify/issues/481
=> Clarify example snippet and link to full example in README

package.json
=> chore(package): update fastify-jwt to version 0.5.0

package.json
=> chore(package): update fastify-jwt to version 0.8.0

package.json
=> ignore-tap

package.json
=> chore(package): update fastify-jwt to version 1.0.0

.gitignore, example.js
1. make it easier for newbies to get started
2. update deps and fix deprecation warnings for beforeHandler
=> make it easier for newbies to get started

package.json
Closes #49 
rimraf 3 dropped node 6
=> greenkeeper-ignore rimraf

fastify-auth.js, test/auth.test.js
=> fix clean status code modified in handler

README.md, fastify-auth.js, test/example-composited.test.js
=> fix 401 statusCode

README.md, example-composited.js, fastify-auth.d.ts, fastify-auth.js, package.json, test/example-composited.test.js, test/types/tsconfig.json, test/types/types.test.ts
Close #61 
`reusify` is quite tricky 😆
=> run all param

auth.d.ts, test/auth.test-d.ts
Sorry for the checklist,, I edit it directly on web interface
=> fix return type

README.md
=> docs(readme): spelling and grammar fixes; http link to https

.gitignore
=> chore(gitignore): add editor files/directories

test/auth.test.js
Issue: https://github.com/fastify/fastify-auth/issues/98
=> Bring auth.js coverage to 100%

test/example.test.js
=> test(example): spelling fixes

test/example.test.js
=> chore: improve coverage for example.js

auth.js
See https://github.com/fastify/fastify-plugin#name
=> chore(auth): add plugin name to metadata

auth.d.ts, package.json, test/auth.test-d.ts
Refs: https://github.com/fastify/fastify-type-provider-typebox/issues/5
=> fix: type propagation

.taprc, test/example-async.js, test/example-async.test.js, test/example-composited.js, test/example-composited.test.js, test/example.js, test/example.test.js
=> restructure tests and enable 100% test coverage check

README.md
=> fix links to examples

LICENSE
=> chore(license): Update license year
